# 基础依赖
pip install transformers==4.34.0 peft==0.4.0 datasets==2.10.1 scipy==1.10.1 tiktoken==0.7.0 transformers_stream_generator==0.0.4
# 量化支持（4bits 微调需安装）
pip install bitsandbytes==0.41.1 accelerate==0.20.3